import { Rubik as Sans } from "next/font/google";
import "@/styles/globals.css";

const sans = Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Simple Next</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${sans.variable} antialiased`}>{children}</body>
    </html>
  );
}
